<?php

 /*               DO NOT EDIT THIS FILE

  Edit the file in the MyComponent config directory
  and run ExportObjects

 */



$packageNameLower = 'loginas';

$components = array(
    'packageName' => 'LoginAs',
    'packageNameLower' => $packageNameLower,
    'packageDescription' => 'Allows login as any user from manager',
    'version' => '0.1.0',
    'release' => 'alpha1',
    'author' => 'Andrey Panyush',
    'email' => '<andreypanyush@gmail.com>',
    'copyright' => '2017',

    'createdon' => strftime('%m-%d-%Y'),

    'gitHubUsername' => 'AndreyPanyush',
    'gitHubRepository' => 'LoginAs',

    'primaryLanguage' => 'ru',

    'dirPermission' => 0755,
    'filePermission' => 0644,

    'mycomponentRoot' => $this->modx->getOption('mc.root', null,
        MODX_CORE_PATH . 'components/mycomponent/'),

    'targetRoot' => MODX_ASSETS_PATH . 'mycomponents/' . $packageNameLower . '/',


    /* *********************** NEW SYSTEM SETTINGS ************************ */

    /* If your extra needs new System Settings, set their field values here.
     * You can also create or edit them in the Manager (System -> System Settings),
     * and export them with exportObjects. If you do that, be sure to set
     * their namespace to the lowercase package name of your extra */

    'newSystemSettings' => array(
        'loginas.token_ttl' => array(
            'key' => 'loginas.token_ttl',
            'name' => 'loginas.setting_ttl',
            'description' => 'loginas.setting_ttl_description',
            'namespace' => 'loginas',
            'xtype' => 'textfield',
            'value' => '300',
            'area' => 'loginas.main',
        ),
        'loginas.remove_read' => array(
            'key' => 'loginas.remove_read',
            'name' => 'loginas.setting_remove_read',
            'description' => 'loginas.setting_remove_read_description',
            'namespace' => 'loginas',
            'xtype' => 'combo-boolean',
            'value' => true,
            'area' => 'loginas.main',
        ),
        'loginas.check_ip' => array(
            'key' => 'loginas.check_ip',
            'name' => 'loginas.setting_check_ip',
            'description' => 'loginas.setting_check_ip_description',
            'namespace' => 'loginas',
            'xtype' => 'combo-boolean',
            'value' => true,
            'area' => 'loginas.main',
        ),
        'loginas.redirect' => array(
            'key' => 'loginas.redirect',
            'name' => 'loginas.setting_redirect',
            'description' => 'loginas.setting_redirect_description',
            'namespace' => 'loginas',
            'xtype' => 'textfield',
            'value' => '',
            'area' => 'loginas.main',
        ),
    ),

    'categories' => array(
        'LoginAs' => array(
            'category' => 'LoginAs',
            'parent' => ''
        )
    ),


    'elements' => array(
        'plugins' => array(
            'LoginAs' => array(
                'category' => 'LoginAs',
                'description' => '',
                'static' => false,
                'events' => array(
                    'OnUserFormPrerender' => array(),
                    'OnWebAuthentication' => array()
                ),
            ),
        )
    ),
    'allStatic' => false,


    'languages' => array(
        'en' => array(
            'default'
        ),
        'ru' => array(
            'default'
        ),
    ),
    /* ********************************************* */
    /* Define optional directories to create under assets.
     * Add your own as needed.
     * Set to true to create directory.
     * Set to hasAssets = false to skip.
     * Empty js and/or css files will be created.
     */
    'hasAssets' => true,

    'assetsDirs' => array(
        'js' => true,
    ),
    'minifyJS' => false,
    'createJSMinAll' => false,
    'useJSMinPlus' => true,
    'jsFiles' => array(
        'mgr/loginas.js',
        'mgr/misc/buttons.js',
        'mgr/widgets/generate.window.js',
    ),
    /* ********************************************* */
    /* Define basic directories and files to be created in project*/

    'docs' => array(
        'readme.txt',
        'license.txt',
        'changelog.txt',
        'tutorial.html'
    ),

    /* (optional) Description file for GitHub project home page */
    'readme.md' => true,
    /* assume every package has a core directory */
    'hasCore' => true,

    /*
    'resolvers' => array(
        'default',
        'addUsers'
    ),*/

    /*
    'validators' => array(
        'default',
        'hasGdLib'
    ),
    */

    /*
    'install.options' => 'install.options',
*/

    /* ********************************************* */
    /* (optional) Only necessary if you will have class files.
     *
     * Array of class files to be created.
     *
     * Format is:
     *
     * 'ClassName' => 'directory:filename',
     *
     * or
     *
     *  'ClassName' => 'filename',
     *
     * ('.class.php' will be appended automatically)
     *
     *  Class file will be created as:
     * yourcomponent/core/components/yourcomponent/model/[directory/]{filename}.class.php
     * Note: If a CMP is being created, classes containing the
     * project name will be ignored here.
     *
     * Set to array() if there are no classes. */
    'classes' => array(
        'LoginAs' => 'loginas:loginas'
    ),

    /* ************************************
     *  These values are for CMPs.
     *  Set any of these to an empty array if you don't need them.
     *  **********************************/

    /* If this is false, the rest of this section will be ignored */

    'createCmpFiles' => true,

    /* IMPORTANT: The array values in the rest of
       this section should be all lowercase */

    /* This is the main action file for your component.
       It will automatically go in core/component/yourcomponent/
    */



    /* These will automatically go to core/components/yourcomponent/processors/
       format directory:filename
       '.class.php' will be appended to the filename

       Built-in processor classes include getlist, create, update, duplicate,
       import, and export. */

    'processors' => array(
        'mgr:generate',
        'web:login',
        ':login'
    ),


    'connectors' => array(
        'connector.php'

    ),

    'cmpJsFiles' => array(
        'mgr:loginas.class.js',
        'mgr/misc:buttons.js',
        'mgr/widgets:generate.window.js',
    ),



    /* *******************************************
     * These settings control exportObjects.php  *
     ******************************************* */
    /* ExportObjects will update existing files. If you set dryRun
       to '1', ExportObjects will report what it would have done
       without changing anything. Note: On some platforms,
       dryRun is *very* slow  */

    'dryRun' => '0',

    /* Array of elements to export. All elements set below will be handled.
     *
     * To export resources, be sure to list pagetitles and/or IDs of parents
     * of desired resources
    */
    'process' => array(
        'plugins',
        'systemSettings',
    ),
    'rewriteCodeFiles' => false,  /* remove ~~descriptions */
    'rewriteLexiconFiles' => true,
    'scriptPropertiesAliases' => array(
        'config',
        'scriptProperties'
    ),
);

return $components;